apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" . }}-sa
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
